### ISSUE TITLE
Thoughts on passing null for missing params instead of throwing?

### ISSUE THREAD

**Issue by matthewaveryusa** [sehrope/node-pg-db#1]
This is more of a philosophical point, but if I submit a pull request that makes missing params null, will you accept it or did you consciously choose to throw? Other alternatives I see are 
-Add an options field to bind with {'bindUndefined':true}, or,
-A brand new function bindOptimistically(...) /_name suggestion are welcome?_/
the code is ~
https://github.com/sehrope/node-pg-db/blob/master/src/named-params.coffee#L125

**Comment by sehrope** [comment]
Rejecting missing params with an error (rather than defaulting to null) was a conscious decision. It's meant to catch things like typos in parameter names. For situations where they value may be missing I usually default the values in the params object via something like `params = {foo: foo || null}`.

I'm not opposed to having it be an option though as long as the default remains unchanged you include a test or two for it.

I think the best way to add it would be to add a `opts` arg to `convertParamValues`. There's no issue with changing the API for the named-param piece as it's purely internal.

The main pg-db function (the one that initializes a main pg-db object) could have the same option with the value defaulted to false. The `opts` arg (on https://github.com/sehrope/node-pg-db/blob/master/src/index.coffee#L383) was meant for things like this though at the moment it's not used for anything.

One catch to this approach would be that it'd be global for all uses of that pg-db instance. The execute/query functions don't have an `opts` arg so there's nowhere to override it. I think I'd like to keep things like that so the API stays simple for them. Again not sure if that'd be an issue for you but something to keep in mind.
